version: '3'
services:
  app:
    build: .
    tty: true # docker run -t
    stdin_open: true # docker run -i
    ports:
      - "8000:8000"
      - "5500:5500"
    volumes:
      - .:/app
      - /app/node_modules
